trigger: none
pr: none

resources:
  pipelines:
    - pipeline: source
      source: windows-server.2025-standard.qemu

stages:
  - template: ../../stages.yml
    parameters:
      sample: development-windows
      image: "2025"
      provider: qemu
