trigger: none
pr: none

resources:
  pipelines:
    - pipeline: source
      source: ubuntu-server.2404-lts.qemu

stages:
  - template: ../../stages.yml
    parameters:
      sample: kitchen-ubuntu
      image: "2404"
      provider: qemu
