trigger: none
pr: none

resources:
  pipelines:
    - pipeline: source
      source: windows-server.2022-standard.qemu

stages:
  - template: ../../stages.yml
    parameters:
      sample: kitchen-windows
      image: "2022"
      provider: qemu
