trigger: none
pr: none

resources:
  pipelines:
    - pipeline: source
      source: windows-server.2025-standard-core.qemu

stages:
  - template: ../../stages.yml
    parameters:
      sample: docker-windows
      image: community-windows-server-core
      provider: qemu
