trigger: none
pr: none

resources:
  pipelines:
    - pipeline: source
      source: ubuntu-server.2404-lts.qemu

stages:
  - template: ../../stages.yml
    parameters:
      sample: ubuntu-desktop
      image: 2404-lts-xubuntu
      provider: qemu
