trigger: none
pr: none

resources:
  pipelines:
    - pipeline: source
      source: ubuntu-server.2204-lts.qemu

stages:
  - template: ../../stages.yml
    parameters:
      sample: ubuntu-desktop
      image: 2204-lts-ubuntu
      provider: qemu
