trigger: none
pr: none

resources:
  pipelines:
    - pipeline: source
      source: ubuntu-server.2204-lts.hyperv

stages:
  - template: ../../stages.yml
    parameters:
      sample: kitchen-ubuntu
      image: "2204"
      provider: hyperv
